#### **1. Import the required packages**

In [ ]:
import numpy as np
import pandas as pd

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split

#### **2. Reading and Exploring the data**

In [ ]:
spam_df = pd.read_csv('emails.csv')

In [ ]:
spam_df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [ ]:
spam_df.shape

(5727, 2)

In [ ]:
spam_df.isnull().sum()

text    0
spam    0
dtype: int64

In [ ]:
spam_df.duplicated().sum()

np.int64(33)

In [ ]:
spam_df.drop_duplicates(inplace = True)

In [ ]:
spam_df['spam'].value_counts() #check for imbalance data

spam
0    4326
1    1368
Name: count, dtype: int64

#### **Vectorizing the text column using CountVectorizer Class**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vectorized_input_data = vectorizer.fit_transform(spam_df['text'])

In [ ]:
vectorized_input_data.shape

(5694, 37298)

In [ ]:
vectorizer.get_feature_names_out()[6000:6100]

array(['bal', 'balaganu', 'balakrishnan', 'balance', 'balanced',
       'balancing', 'balasaheb', 'balasubramanian', 'balcerowiczem',
       'baldick', 'baldock', 'baldwin', 'balkis', 'balko', 'ball',
       'balla', 'ballance', 'ballers', 'balloon', 'ballot', 'balloting',
       'ballroom', 'balmat', 'baltes', 'baltic', 'baltimore', 'baltz',
       'bama', 'bambi', 'bambos', 'bammel', 'ban', 'banc', 'bancware',
       'band', 'bandaid', 'bandar', 'bandeaux', 'banded', 'bandh',
       'bandini', 'bandit', 'bands', 'bandwidth', 'bandwidths',
       'bandyopadhyay', 'baneberry', 'banerjea', 'banerjee', 'bang',
       'bangalore', 'bangkok', 'bangles', 'bangs', 'bani', 'banian',
       'bank', 'banked', 'banken', 'banker', 'bankers', 'bankgirolotto',
       'banking', 'bankowe', 'bankructwa', 'bankrupt', 'bankruptcies',
       'bankruptcy', 'banks', 'bannantine', 'banned', 'banner',
       'bannerco', 'bannerghatta', 'banners', 'bannersgomlm', 'banque',
       'banquet', 'bansal', 'bantus', 'bapat', 'bar', 'barabara', 'baran',
       'baraniuk', 'barb', 'barbados', 'barbara', 'barbarian', 'barbaric',
       'barbarous', 'barbecue', 'barbeque', 'barber', 'barbera',
       'barbituric', 'barcelona', 'barcharts', 'barclays', 'bard'],
      dtype=object)

### **Machine Learning Process**

In [ ]:
X = vectorized_input_data
y = spam_df['spam']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y)

#### **Apply the algorithm on the data**

**There are three variants of Naive Bayes Classifier:**

1. Gaussian NB
2. Bernoulli NB
3. Multinomial NB

In [ ]:
multi_nb = MultinomialNB()
multi_nb.fit(X_train, y_train)

MultinomialNB()

In [ ]:
y_pred = multi_nb.predict(X_test)

In [ ]:
roc_auc_score(y_test, y_pred)

np.float64(0.9887452006244462)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

Model Accuracy: 98.86%

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[855  10]
 [  3 271]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       865
           1       0.96      0.99      0.98       274

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.98      1139
weighted avg       0.99      0.99      0.99      1139

#### **Let's try the model on some new unseen emails**

In [ ]:
emails = ['Congratulations, you have a pre-approved loan of 5000 US Dollars. No documentation required.',
          'Can we have a quick meeting tomorrow at 5 PM ?']

In [ ]:
transformed_emails = vectorizer.transform(emails)

In [ ]:
multi_nb.predict(transformed_emails)

array([1, 0])

In [ ]:
import joblib
joblib.dump(vectorizer, 'vectorizer.pkl')
joblib.dump(multi_nb, 'spam_model.pkl')
print('Model and vectorizer saved successfully!')